# Permalinks
permalink:           pretty

# Setup
title:               Austin Guiney
tagline:             "Inside the mind of Austin Guiney!"
baseurl:             ""
paginate:            10
url:                 https://www.austinguiney.com

exclude: [Rakefile, 
          _posts/LICENSE.md,
          _data/comments/LICENSE.md,
          _assets/img/IMAGE_LICENSE.md,
          _assets/img/svg/licenses/,
          LICENSE.md, 
          CONTRIBUTORS.md, 
          staticman.yml, 
          TODO.txt, 
          README.md, 
          node_modules, 
          package.json, 
          gulpfile.js,
          vendor,
          _assets,
          Gemfile,
          Gemfile.lock,
          yarn-error.log,
          yarn.lock,
          package-lock.json,
          update-comments.sh]

# Name of repository, for use with Staticman
repository: "pyreking/pyreking.github.io"

# Staticman comments (see staticman.yml for configuration).
staticman:
  branch: "source"

# About/contact
author:
  name:              Austin Guiney
  url:               https://twitter.com/SenorKoffey
  email:             austin.guiney@gmail.com

# Gems
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  
# Post preview
excerpt_separator: <!--more-->

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: year
    month: month
    day: day
    tag: tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    
compress_html:
  clippings: []
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
