# Permalinks
permalink:           pretty

# Setup
title:               Austin Guiney
tagline:             "Inside the mind of Austin Guiney!"
url:                 http://austinguiney.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Austin Guiney
  url:               https://twitter.com/SenorKoffey
  email:             austin.guiney@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pyreking.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives
  
# Post preview
excerpt_separator: <!--more-->

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: year
    month: month
    day: day
    tag: tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
