# Permalinks
permalink:           pretty

# Setup
title:               Austin Guiney
tagline:             "Inside the mind of Austin Guiney!"
paginate:            10
baseurl:             ""

exclude: [Rakefile, _posts/LICENSE.md, _data/comments/LICENSE.md]

# Name of repository, for use with Staticman
repository: "pyreking/pyreking.github.io"

# Staticman comments (see staticman.yml for configuration).
staticman:
  branch: "master"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Austin Guiney
  url:               https://twitter.com/SenorKoffey
  email:             austin.guiney@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives
  - jekyll-sitemap
  
# Post preview
excerpt_separator: <!--more-->

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: year
    month: month
    day: day
    tag: tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
